apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dc-podman-volume-bootstrap
  description: OSS, rootless-podman equivalent of "Clone Repository in Container Volume" for dev containers
  annotations:
    github.com/project-slug: 4ld4z4b4l/dc-podman-volume-bootstrap
    backstage.io/techdocs-ref: dir:.
  tags:
    - devcontainer
    - podman
    - rootless
    - oci
    - cli
spec:
  type: tool
  lifecycle: experimental
  owner: 4ld4z4b4l